export const Product = [
    {Qty:"Processor", selectedItem: null, name: "Processor", title:"Select Processor", img:"https://www.pcstudio.in/wp-content/uploads/2021/04/processor-caticon.svg"},
    {Qty:"Motherboard", selectedItem: null, name: "Motherboard", title:"Select Motherboard", img:"https://www.pcstudio.in/wp-content/uploads/2021/04/motherboard-caticon.svg"},
    {Qty:"Ram", selectedItem: null, name: "Ram", title:"Select RAM", img:"https://www.pcstudio.in/wp-content/uploads/2021/04/ram-caticon.svg"},
    {Qty:"Storage1", selectedItem: null, name: "Storage1", title:"Select Storage 1", img:"https://www.pcstudio.in/wp-content/uploads/2021/04/storage-caticon.svg"},
    {Qty:"Storage2", selectedItem: null, name: "Storage2", title:"Select Storage 2", img:"https://www.pcstudio.in/wp-content/uploads/2021/04/storage-caticon.svg"},
    {Qty:"Cabinet", selectedItem: null, name: "Cabinet", title:"Select Cabinet", img:"https://www.pcstudio.in/wp-content/uploads/2021/04/cabinets-caticon.svg"},
    {Qty:"Cabinetfan", selectedItem: null, name: "Cabinetfan", title:"Select Cabinet Fan", img:"https://www.pcstudio.in/wp-content/uploads/2021/04/cabinetfan-caticon.svg"},
    {Qty:"Cooler", selectedItem: null, name: "Cooler", title:"Select Cooler", img:"https://www.pcstudio.in/wp-content/uploads/2021/04/cooler-caticon.svg"},
    {Qty:"Graphicscard", selectedItem: null, name: "Graphicscard", title:"Select Graphics Card", img:"https://www.pcstudio.in/wp-content/uploads/2021/04/graphiccard-caticon.svg"},
    {Qty:"Powersupplyunit", selectedItem: null, name: "Powersupplyunit", title:"Select Power Supply Unit", img:"https://www.pcstudio.in/wp-content/uploads/2021/04/powersupply-caticon.svg"},
    {Qty:"Monitor", selectedItem: null, name: "Monitor", title:"Select Monitor", img:"https://www.pcstudio.in/wp-content/uploads/2021/04/monitor-caticon.svg"},
    {Qty:"Keyboard", selectedItem: null, name: "Keyboard", title:"Select Keyboard", img:"https://www.pcstudio.in/wp-content/uploads/2021/04/keyboard-caticon.svg"},
    {Qty:"Mouse", selectedItem: null, name: "Mouse", title:"Select Mouse", img:"https://www.pcstudio.in/wp-content/uploads/2021/04/mouse-caticon.svg"},
    {Qty:"Accessories", selectedItem: null, name: "Accessories", title:"Select Accessories", img:"https://www.pcstudio.in/wp-content/uploads/2021/04/gaminglaptop-caticon.svg"},
]